# Generated by Django 5.0.6 on 2024-06-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_waitinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='user',
        ),
    ]
