# Generated by Django 5.0.6 on 2024-06-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='users.payment'),
        ),
    ]
